# Generated by Django 4.1.5 on 2023-03-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='descriptive_name',
            field=models.CharField(max_length=100),
        ),
    ]
