# Generated by Django 4.1.5 on 2023-04-04 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algo_trading', '0006_alter_instrument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OhlcvDataDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='trade time')),
                ('open', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='open price')),
                ('high', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='high price')),
                ('low', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='low price')),
                ('close', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='close price')),
                ('volume', models.IntegerField(verbose_name='trade volume')),
                ('dividends', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='dividends')),
                ('splits', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='splits')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='algo_trading.instrument')),
            ],
            options={
                'verbose_name': 'OhlcvDataDaily',
                'verbose_name_plural': 'OhlcvDataDailies',
                'get_latest_by': 'date',
                'order_with_respect_to': 'instrument',
            },
        ),
        migrations.AddIndex(
            model_name='ohlcvdatadaily',
            index=models.Index(fields=['date'], name='ohlcv_daily_date_idx'),
        ),
        migrations.AddIndex(
            model_name='ohlcvdatadaily',
            index=models.Index(fields=['instrument', 'date'], name='ohlcv_dly_instrument_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='ohlcvdatadaily',
            constraint=models.UniqueConstraint(fields=('instrument', 'date'), name='unique_instrument_ohlcv_data_daily_date', violation_error_message='Date for instrument already exists, must be unique'),
        ),
    ]
