# Generated by Django 4.1.5 on 2023-04-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_trading', '0008_remove_ohlcvdatadaily_dividends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='zerodha_instrument_token',
            field=models.IntegerField(default=0, verbose_name='zerodha instrument token'),
        ),
    ]
