# Generated by Django 4.1.5 on 2023-04-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo_trading', '0010_alter_ohlcvdatadaily_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='ohlcvdatadaily',
            order_with_respect_to=None,
        ),
    ]
