# Generated by Django 4.1.5 on 2023-04-11 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algo_trading', '0012_delete_ohlcvdatadaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='OhlcDataDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='trade time')),
                ('open', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='open price')),
                ('high', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='high price')),
                ('low', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='low price')),
                ('close', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='close price')),
                ('last_price', models.DecimalField(decimal_places=5, default=0.0, max_digits=15, verbose_name='last price')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='algo_trading.instrument')),
            ],
            options={
                'get_latest_by': 'date',
            },
        ),
        migrations.AddIndex(
            model_name='ohlcdatadaily',
            index=models.Index(fields=['date'], name='ohlcv_daily_date_idx'),
        ),
        migrations.AddIndex(
            model_name='ohlcdatadaily',
            index=models.Index(fields=['instrument', 'date'], name='ohlcv_dly_instrument_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='ohlcdatadaily',
            constraint=models.UniqueConstraint(fields=('instrument', 'date'), name='unique_instrument_ohlcv_data_daily_date', violation_error_message='Date for instrument already exists, must be unique'),
        ),
    ]
