# Generated by Django 4.1.5 on 2023-04-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo_trading', '0013_ohlcdatadaily_ohlcdatadaily_ohlcv_daily_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ohlcdatadaily',
            options={'get_latest_by': 'date', 'verbose_name': 'OhlcDataDaily', 'verbose_name_plural': 'OhlcDataDailies'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='ohlcdatadaily',
            order_with_respect_to='instrument_id',
        ),
    ]
