# Generated by Django 4.1.5 on 2023-04-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo_trading', '0014_alter_ohlcdatadaily_options_and_more'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='ohlcdatadaily',
            order_with_respect_to=None,
        ),
    ]
