# Generated by Django 4.1.9 on 2023-05-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo_trading', '0015_alter_ohlcdatadaily_order_with_respect_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='descriptive_name',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='first_open_date',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='zerodha_exchange',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='zerodha_exchange_token',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='zerodha_instrument_token',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='zerodha_lot_size',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='zerodha_segment',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='zerodha_trading_symbol',
        ),
    ]
