# Generated by Django 4.1.9 on 2023-05-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_trading', '0016_remove_instrument_descriptive_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='exchange',
            field=models.CharField(default='', max_length=50, verbose_name='zerdoha exchange'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='exchange_token',
            field=models.CharField(default='', max_length=100, verbose_name='zerodha exchange token'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='expiry',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='zerodha expiry date'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_token',
            field=models.IntegerField(default=0, verbose_name='zerodha instrument token'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='lot_size',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='zerodha lot size'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='zerodha company name'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='segment',
            field=models.CharField(default='', max_length=50, verbose_name='zerodha segment'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='strike',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=15, null=True, verbose_name='zerodha strike price'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='tick_size',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=15, null=True, verbose_name='zerodha tick size'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='trading_symbol',
            field=models.CharField(default='', max_length=100, verbose_name='zerodha trading symbol'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(choices=[('EQ', 'Equity'), ('FUT', 'Futures'), ('CE', 'Call Option'), ('PE', 'Put Option'), ('IX', 'Index'), ('CU', 'Currency'), ('CF', 'Currency Futures'), ('CO', 'Currency Options'), ('IF', 'Index Futures'), ('IO', 'Index Options')], default='EQ', max_length=3),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='symbol',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['trading_symbol', 'exchange'], name='instrument_identifier_idx'),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('trading_symbol', ''), _negated=True), models.Q(('exchange', ''), _negated=True)), fields=('trading_symbol', 'exchange'), name='unique_instrument_identifier', violation_error_message='Instrument name at exchange already exists'),
        ),
    ]
