# Generated by Django 4.1.9 on 2023-06-01 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algo_trading", "0017_instrument_exchange_instrument_exchange_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="created at")),
                ("fulfilled_at", models.DateTimeField(verbose_name="fulfilled at")),
                ("exited_at", models.DateTimeField(verbose_name="exited at")),
                (
                    "signal_source",
                    models.CharField(
                        default="", max_length=100, verbose_name="source of signal"
                    ),
                ),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("EQ", "Equity"),
                            ("FUT", "Futures"),
                            ("CE", "Call Option"),
                            ("PE", "Put Option"),
                            ("IX", "Index"),
                            ("CU", "Currency"),
                            ("CF", "Currency Futures"),
                            ("CO", "Currency Options"),
                            ("IF", "Index Futures"),
                            ("IO", "Index Options"),
                        ],
                        default="EQ",
                        max_length=4,
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(
                        choices=[("BUY", "BUY"), ("SELL", "SELL")],
                        default="BUY",
                        max_length=4,
                    ),
                ),
                (
                    "entry_point",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        default=None,
                        max_digits=15,
                        null=True,
                        verbose_name="entry point",
                    ),
                ),
                (
                    "stoploss_point",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        default=None,
                        max_digits=15,
                        null=True,
                        verbose_name="stoploss point",
                    ),
                ),
                (
                    "target1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        default=None,
                        max_digits=15,
                        null=True,
                        verbose_name="target 1",
                    ),
                ),
                (
                    "target2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        default=None,
                        max_digits=15,
                        null=True,
                        verbose_name="target 2",
                    ),
                ),
                (
                    "target3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        default=None,
                        max_digits=15,
                        null=True,
                        verbose_name="target 3",
                    ),
                ),
                (
                    "lot_size",
                    models.IntegerField(
                        blank=True, default=None, null=True, verbose_name="lot size"
                    ),
                ),
                (
                    "tick_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        default=None,
                        max_digits=15,
                        null=True,
                        verbose_name="tick size",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algo_trading.instrument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trading Signal",
                "verbose_name_plural": "Trading Signals",
                "get_latest_by": "id",
            },
        ),
        migrations.AddIndex(
            model_name="tradingsignal",
            index=models.Index(fields=["instrument_id"], name="signal_instrument_id"),
        ),
        migrations.AddIndex(
            model_name="tradingsignal",
            index=models.Index(
                fields=["signal_type", "instrument_id"],
                name="signal_type_and_instrument",
            ),
        ),
    ]
