# Generated by Django 4.1.9 on 2023-06-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "algo_trading",
            "0018_tradingsignal_tradingsignal_signal_instrument_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingsignal",
            name="exited_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="exited at"
            ),
        ),
        migrations.AlterField(
            model_name="tradingsignal",
            name="fulfilled_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="fulfilled at"
            ),
        ),
    ]
