# Generated by Django 4.1.9 on 2023-06-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algo_trading", "0019_alter_tradingsignal_exited_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingsignal",
            name="entry_point",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                max_digits=15,
                null=True,
                verbose_name="entry point",
            ),
        ),
        migrations.AlterField(
            model_name="tradingsignal",
            name="stoploss_point",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                max_digits=15,
                null=True,
                verbose_name="stoploss point",
            ),
        ),
        migrations.AlterField(
            model_name="tradingsignal",
            name="target1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                max_digits=15,
                null=True,
                verbose_name="target 1",
            ),
        ),
        migrations.AlterField(
            model_name="tradingsignal",
            name="target2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                max_digits=15,
                null=True,
                verbose_name="target 2",
            ),
        ),
        migrations.AlterField(
            model_name="tradingsignal",
            name="target3",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                max_digits=15,
                null=True,
                verbose_name="target 3",
            ),
        ),
    ]
