# Generated by Django 4.1.9 on 2023-06-05 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algo_trading", "0020_alter_tradingsignal_entry_point_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trading_symbol",
                    models.CharField(
                        default="", max_length=100, verbose_name="trading symbol"
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        default="", max_length=50, verbose_name="zerdoha exchange"
                    ),
                ),
                (
                    "order_id",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="zerodha order id",
                    ),
                ),
                (
                    "exchange_order_id",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="exchange order id",
                    ),
                ),
                (
                    "trigger_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=15,
                        null=True,
                        verbose_name="order trigger price",
                    ),
                ),
                (
                    "average_entry_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=15,
                        null=True,
                        verbose_name="average entry price",
                    ),
                ),
                (
                    "average_closing_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=15,
                        null=True,
                        verbose_name="average close price",
                    ),
                ),
                ("quantity", models.IntegerField(default=0, verbose_name="quantity")),
                (
                    "margin_invested",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=15,
                        null=True,
                        verbose_name="margin invested",
                    ),
                ),
                (
                    "placed_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="order placed at",
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="order executed at",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="order closed at",
                    ),
                ),
                (
                    "p_and_l",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="total P&L",
                    ),
                ),
                (
                    "p_and_l_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="P&L percentage",
                    ),
                ),
                (
                    "closing_duration",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="close duration",
                    ),
                ),
                (
                    "status_msg",
                    models.CharField(
                        default="",
                        max_length=200,
                        verbose_name="status msg from broker",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("M", "MARKET"),
                            ("L", "LIMIT"),
                            ("SL", "STOPLOSS_LIMIT"),
                            ("SL-M", "STOPLOSS MARKET"),
                        ],
                        default="L",
                        max_length=5,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("CNC", "Cash and Carry"),
                            ("MIS", "Margin Intraday Squareoff"),
                            ("NRML", "NORMAL"),
                        ],
                        default="NRML",
                        max_length=5,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        default="BUY",
                        max_length=4,
                    ),
                ),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("EQ", "Equity"),
                            ("FUT", "Futures"),
                            ("CE", "Call Option"),
                            ("PE", "Put Option"),
                            ("IX", "Index"),
                            ("CU", "Currency"),
                            ("CF", "Currency Futures"),
                            ("CO", "Currency Options"),
                            ("IF", "Index Futures"),
                            ("IO", "Index Options"),
                        ],
                        default="CE",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "PUT ORDER REQ RECEIVED",
                                "Order request received by broker",
                            ),
                            ("VALIDATION PENDING", "Order pending validation by RMS"),
                            (
                                "OPEN_PENDING",
                                "Order is pending registration at the exchange",
                            ),
                            (
                                "MODIFY VALIDATION PENDING",
                                "Order's modification values are pending validation by the RMS",
                            ),
                            (
                                "MODIFY PENDING",
                                "Order's modification values are pending registration at the exchange",
                            ),
                            (
                                "MODIFIED",
                                "Order modification successfully applied at exchange",
                            ),
                            (
                                "TRIGGER PENDING",
                                "Order's placed but the fill is pending based on a trigger price.",
                            ),
                            (
                                "CANCEL PENDING",
                                "Order's cancellation request is pending registration at the exchange",
                            ),
                            (
                                "AMO REQ RECEIVED",
                                "Same as PUT ORDER REQ RECEIVED, but for AMOs",
                            ),
                            ("OPEN", "Order still open at exchange"),
                            ("CANCELLED", "Order cancelled by exchange"),
                            ("REJECTED", "Order rejected by exchange"),
                            ("COMPLETE", "Order completed at exchange"),
                        ],
                        default="PUT ORDER REQ RECEIVED",
                        max_length=40,
                    ),
                ),
                (
                    "trading_signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algo_trading.tradingsignal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["trading_symbol"], name="order_trading_symbol_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["trading_signal"], name="order_trading_signal_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["instrument_type"], name="order_instrument_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["product_type"], name="order_product_type_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="order_status_idx"),
        ),
    ]
