# Generated by Django 4.1.9 on 2023-06-05 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algo_trading", "0021_order_order_order_trading_symbol_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="trading_signal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="algo_trading.tradingsignal",
            ),
        ),
    ]
