# Generated by Django 4.1.9 on 2023-06-05 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algo_trading", "0022_alter_order_trading_signal_delete_ohlcdatadaily"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="status change time",
                    ),
                ),
                (
                    "cancelled_quantity",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="cancelled quantity",
                    ),
                ),
                (
                    "filled_quantity",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="filled quantity",
                    ),
                ),
                (
                    "pending_quantity",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="pending quantity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "PUT ORDER REQ RECEIVED",
                                "Order request received by broker",
                            ),
                            ("VALIDATION PENDING", "Order pending validation by RMS"),
                            (
                                "OPEN_PENDING",
                                "Order is pending registration at the exchange",
                            ),
                            (
                                "MODIFY VALIDATION PENDING",
                                "Order's modification values are pending validation by the RMS",
                            ),
                            (
                                "MODIFY PENDING",
                                "Order's modification values are pending registration at the exchange",
                            ),
                            (
                                "MODIFIED",
                                "Order modification successfully applied at exchange",
                            ),
                            (
                                "TRIGGER PENDING",
                                "Order's placed but the fill is pending based on a trigger price.",
                            ),
                            (
                                "CANCEL PENDING",
                                "Order's cancellation request is pending registration at the exchange",
                            ),
                            (
                                "AMO REQ RECEIVED",
                                "Same as PUT ORDER REQ RECEIVED, but for AMOs",
                            ),
                            ("OPEN", "Order still open at exchange"),
                            ("CANCELLED", "Order cancelled by exchange"),
                            ("REJECTED", "Order rejected by exchange"),
                            ("COMPLETE", "Order completed at exchange"),
                        ],
                        default=None,
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "status_message",
                    models.CharField(
                        max_length=200, verbose_name="status change message"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algo_trading.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order History",
                "verbose_name_plural": "Order Histories",
            },
        ),
        migrations.AddIndex(
            model_name="orderhistory",
            index=models.Index(fields=["status"], name="order_history_status_idx"),
        ),
        migrations.AddIndex(
            model_name="orderhistory",
            index=models.Index(fields=["order"], name="order_history_order_idx"),
        ),
    ]
