# Generated by Django 4.1.9 on 2023-06-05 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "algo_trading",
            "0025_alter_order_trading_signal_alter_orderhistory_order_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="trading_signal",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trading_signal",
                to="algo_trading.tradingsignal",
            ),
        ),
    ]
