# Generated by Django 4.1.9 on 2023-06-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algo_trading", "0026_alter_order_trading_signal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderhistory",
            name="status_message",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                verbose_name="status change message",
            ),
        ),
    ]
